### PR TITLE
Integrated into qt-pods.

### PR DESCRIPTION
**Pull request by cybercatalyst**

### CODE REVIEW

**Comment by sladage** [comment]
Looks good, but please don't use `#pragma once`.

**Comment by cybercatalyst** [comment]
What's the problem with it?

**Comment by sladage** [comment]
It's non-standard. Granted, most compilers support it now, but I prefer not to assume everyone is using a compiler with pragma once support.

**Comment by cybercatalyst** [comment]
Ok, I replaced the #pragma once. I will have a further read on this later. Will you be actively maintaining the project? I would like to set your repository as the main source for QtLZMA.

**Comment by sladage** [comment]
Yeah, not have much time currently but still plan on making some improvements in the near future.

**Pull request merged**
